spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hanjunchao-github/spring-cloud/tree/test
          searchPaths: profile,profile/bank,profile/respo
          username: hanjunchao-github
          password: xiaohan-0614
        prefix: spring-cloud/config
      label: master

  application:
    name: spring-cloud-config

server:
  port: 8888

#logging:
#  level:
#    root: debug


